### ISSUE TITLE
複数ウィンドウで開いた時のエラーが分かりにくい

### ISSUE THREAD

**Issue by rasp753** [chirimen-oh/chirimen-drivers#14]
複数ウィンドウで開いた時のエラーが、コンソールに「initに失敗した」と出るだけで、複数ウィンドウを開いたことが原因であるとわかりにくい。

**Comment by kou029w** [comment]
関連: https://github.com/chirimen-oh/chirimen-raspi3/issues/80

**Comment by kou029w** [comment]
chirimen-oh/chirimen#80 にて解決
