### ISSUE TITLE
node.jsでESModuleとして使おうとするとエラーアウトする

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-drivers#149]
> To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

各ドライバのpackage.jsonに、"type": "module"を追加することで動作するようになりました。
が、サイドエフェクトは無いでしょうか？　無ければすべてのドライバのpackage.jsonに"type": "module"を追加すべきと思います。
ちなみにこんなコードを書いています。
```javascript
import {requestI2CAccess} from "./node_modules/node-web-i2c/index.js";
import ADT7410 from "./node_modules/@chirimen/adt7410/adt7410.js";
const sleep = msec => new Promise(resolve => setTimeout(resolve, msec));
async function measure() {
  const i2cAccess = await requestI2CAccess();
  const i2c1 = i2cAccess.ports.get(1);
  const adt7410 = new ADT7410(i2c1, 0x48);
  await adt7410.init();

  while(true){
    const temperature = await adt7410.read();
    console.log(`Temperature: ${temperature} ℃`);
    await sleep(1000);
  }
}

measure();
```

**Comment by kou029w** [comment]
副作用はあると考えます。CHIRIMEN環境でバンドラー等を介して従来の index.js を使おうとすると意図せず読み込めない可能性が考えられます。
ところで、下記ではインポートに失敗しますか?

```js
import ADT7410 from "@chirimen/adt7410";
```

参考: README.md

**Comment by satakagi** [comment]
あ、READMEに書かれていたんですね。
ちなにみこの書き方でうまくライブラリが読み込めるのは何かnode.js特有の機能に依るのでしょうか？
ファイルパスを明示しなくても読み込めているので何か特別な機能なのかなと思いますが。

**Comment by kou029w** [comment]
> ちなにみこの書き方でうまくライブラリが読み込めるのは何かnode.js特有の機能に依るのでしょうか？

はい。おっしゃるとおりです。こちらのドキュメントにあるNode.jsの振る舞いです。
ドキュメント: https://nodejs.org/api/packages.html

**Comment by kou029w** [comment]
特有かどうか、という観点で言うと、実は特有ではないですね。訂正します。
標準化の提案はTC39 [tc39/proposal\-import\-assertions: Proposal for syntax to import ES modules with assertions](https://github.com/tc39/proposal-import-assertions) にてあり、現時点ではStage 3です。

**Comment by satakagi** [comment]
https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/es-examples/ADT7410
のサンプルは
```javascript
import ADT7410 from "@chirimen/adt7410";
```
でつくりました。closeしますね。
