### ISSUE TITLE
node-web-i2cに関数が実装された後に動作確認が必要

### ISSUE THREAD

**Issue by rasp753** [chirimen-oh/chirimen-drivers#15]
https://github.com/kou029w/node-web-i2c/issues/1#issue-523805604
- I2CPort.prototype.writeByte
- I2CPort.prototype.writeBytes
- I2CPort.prototype.readByte
- I2CPort.prototype.readBytes

下記のexampleについては、上記のissueが解決するまで動作確認ができないためissue解決後に動作確認が必要。

- [x] S11059のNode.js用example (I2CPort.prototype.writeByteの実装待ち)

**Comment by kou029w** [comment]
node-web-i2c@1.1.1にて動作確認して問題なかったのでクローズ
