### ISSUE TITLE
SSD1306 対応

### ISSUE THREAD

**Issue by kou029w** [chirimen-oh/chirimen-drivers#58]
https://github.com/chirimen-oh/chirimen にある [i2c-grove-oled-display](https://github.com/chirimen-oh/chirimen/blob/fca0d6d5f6a257f68d4406e20f081b868285f3c4/gc/i2c/i2c-grove-oledDisplay/node_modules/%40chirimen-raspi/chirimen-driver-i2c-grove-oled-display/OledDisplay.js) を参考にしつつSSD1306に対応する

**Comment by rasp753** [comment]
対応完了　https://github.com/chirimen-oh/chirimen-drivers/commit/fc77e4ad2f8e741d56a37b4f512f37f58df60430
