### ISSUE TITLE
動作確認しているものに関してはnode.js用サンプルコードを提供

### ISSUE THREAD

**Issue by kou029w** [chirimen-oh/chirimen-drivers#8]
CHIRIMEN Examplesのなかのコードに倣って、node.jsからも利用できるようにサンプルコードを提供する

アップデートされた現在最新のパッケージ

- [x] @chirimen/ads1015@1.0.1-alpha.1
- [x] @chirimen/adt7410@1.0.1-alpha.0
- [x] @chirimen/gp2y0e03@1.0.1-alpha.0
- [x] @chirimen/grove-accelerometer(adxl345)@1.0.0-alpha.1
- [x] @chirimen/grove-gesture@1.0.0-alpha.1
- [x] @chirimen/grove-light@1.0.0-alpha.4
- [x] @chirimen/grove-oled-display@1.0.0-alpha.1
- [x] @chirimen/grove-touch@1.0.0-alpha.1
- [x] @chirimen/pca9685@1.0.1-alpha.0
- [x] @chirimen/s11059@1.0.2-alpha.0
- [x] @chirimen/veml6070@1.0.0-alpha.1
- [x] @chirimen/vl53l0x@1.0.3-alpha.0

**Comment by kou029w** [comment]
アップデートされた現在最新のパッケージ

- [ ] @chirimen/ads1015@1.0.1-alpha.1
- [ ] @chirimen/adt7410@1.0.1-alpha.0
- [ ] @chirimen/gp2y0e03@1.0.1-alpha.0
- [ ] @chirimen/grove-accelerometer@1.0.0-alpha.1
- [ ] @chirimen/grove-gesture@1.0.0-alpha.1
- [ ] @chirimen/grove-light@1.0.0-alpha.4
- [ ] @chirimen/grove-oled-display@1.0.0-alpha.1
- [ ] @chirimen/grove-touch@1.0.0-alpha.1
- [ ] @chirimen/pca9685@1.0.1-alpha.0
- [ ] @chirimen/s11059@1.0.2-alpha.0
- [ ] @chirimen/veml6070@1.0.0-alpha.1
- [ ] @chirimen/vl53l0x@1.0.3-alpha.0

**Comment by rasp753** [comment]
ADT7410でテスト時にOperationErrorが発生　#23 
node用サンプルは作成済みのため、エラー解消後再テスト

**Comment by rasp753** [comment]
Grove touch sensorのNode.js用exampleでbindings.jsにエラーが発生 #28

**Comment by kou029w** [comment]
主要なモジュールは一通り動作確認できたのでクローズ
