### ISSUE TITLE
/raspi-examples, /microbit-examples にgithubpagesでアクセスできない

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-drivers#98]
@dynamis 
今は/docs　以下でgithubpagesが作られるようになっていますよね？
これだと↑のディレクトリへ直接アクセスできないです。

githubpagesで、CHIRIMEN Examplesを直接開くというケースに対応できません。

githubpagesの生成を/docs/ 以下に絞る理由がわかりません。 /以下全部githubpagesで公開できるように修正をお願いします。

**Comment by satakagi** [comment]
急ぎで公開が必要なので、/raspi-examples, /microbit-examplesのコピーを/docsに置きます・・・・

**Comment by satakagi** [comment]
Settingsで公開のルートを/に変更できるようです。
/docs/をルートにする妥当な理由があり意義のある方が居なければセッティングを変更します。
とりあえず期限を2020/12月中とします。

**Comment by kou029w** [comment]
変更しましょう

**Comment by kou029w** [comment]
変更しました

**Comment by satakagi** [comment]
外部コンテンツで/docsに張っていたものを直しましたので、closeします。
